### ISSUE TITLE
Sinkron Pendapatan dan Pembiayaan tidak berjalan

### ISSUE THREAD

**Issue by ireene83** [agusnurwanto/sipd-ri-chrome-extension#29]
Sinkron Data Pendapatan hanya 1 unit yg paling atas yang berhasil diimport ke db lokal, sedangkan lainnya tidak bisa,  untuk pembiayaan masih belum bisa berjalan baik pembiayaan penerimaan maupun pembiayaan pengeluaran. Terima kasih..

**Comment by bangil0** [comment]
terima kasih atas masukkan, akan segera kami coba kembali dan perbaiki

**Comment by bangil0** [comment]
setelah dipelajari ternyata ada perubahan struktur data pasa sipd-ri,  [fixed](https://github.com/agusnurwanto/sipd-ri-chrome-extension/commit/412622825bd2f266290523bc556e82040bf59b79)
